
const ItemList = [
    {
      id:1,
      image:'/photo/prakash1.png',
      price:'10',
      title:'Item1'              
    },
    {
      id:2,
      image:'/photo/prakash2.png',
      price:'20',
      title:'Items2'
    },
    {
      id:3,
      image:'/photo/prakash3.png',
      price:'30',
      title:'Item3'
    },
    {
      id:4,
      image:'/photo/prakash4.png',
      price:'40',
      title:'Item4'
    },
    {
      id:5,
      image:'/photo/prakash5.png',
      price:'50',
      title:'Item5'
    },
    {
      id:6,
      image:'/photo/prakash6.png',
      price:'60',
      title:'Item6'
    },
    {
      id:7,
      image:'/photo/prakash7.png',
      price:'60',
      title:'Item6'
    },
    {
      id:8,
      image:'/photo/prakash8.png',
      price:'60',
      title:'Item6'
    }
]
export default ItemList;
